import "./globals.css";
// import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
//redux
import { Providers } from "@/app/Redux/provider";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Nike Store",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,700;1,600&display=swap"
        rel="stylesheet"
      ></link> */}

      <body className={nunito.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
